src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $raisonSociale = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateCreation = null;

    #[ORM\Column(length: 100)]
    private ?string $adresse = null;

    #[ORM\Column(length: 20)]
    private ?string $cp = null;

    #[ORM\Column(length: 50)]
    private ?string $ville = null;

    /**
     * @var Collection<int, Employe>
     */
    #[ORM\OneToMany(targetEntity: Employe::class, mappedBy: 'entreprise', orphanRemoval: true)]
    // on ajoute cette annotation sur la collection d'employés pour trier les employés par nom
    #[ORM\OrderBy(["nom" => "ASC"])]
    private Collection $employes;

    public function __construct()
    {
        $this->employes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raisonSociale;
    }

    public function setRaisonSociale(string $raisonSociale): static
    {
        $this->raisonSociale = $raisonSociale;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): static
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): static
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAdresseComplete(): ?string
    {
        return $this->adresse." ".$this->cp." ".$this->ville;
    }

    /**
     * @return Collection<int, Employe>
     */
    public function getEmployes(): Collection
    {
        return $this->employes;
    }

    public function addEmploye(Employe $employe): static
    {
        if (!$this->employes->contains($employe)) {
            $this->employes->add($employe);
            $employe->setEntreprise($this);
        }

        return $this;
    }

    public function removeEmploye(Employe $employe): static
    {
        if ($this->employes->removeElement($employe)) {
            // set the owning side to null (unless already changed)
            if ($employe->getEntreprise() === $this) {
                $employe->setEntreprise(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->raisonSociale; // ." (".$this->cp." ".$this->ville.")"
    }
}

src/Form/EntrepriseType.php
<?php

namespace App\Form;

use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class EntrepriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('raisonSociale', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('dateCreation', DateType::class, [
                // attribut qui permet d'avoir un calendrier dans l'input DateType
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('adresse', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('cp', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('ville', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('valider', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Entreprise::class,
        ]);
    }
}

src/Controller/EntrepriseController.php
<?php

namespace App\Controller;

use App\Entity\Entreprise;
use App\Form\EntrepriseType;
use App\Repository\EntrepriseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EntrepriseController extends AbstractController
{
    
    // exemple
    // public function index(): Response 
    // {
        //     $name = 'Elan Formation';
        //     $tableau = ['valeur 1', 'valeur 2', 'valeur 3'];
        
        //     // cette méthode permet de faire le lien entre le controller et la vue
        //     return $this->render('entreprise/index.html.twig', [
            //             // 'variable' => 'chaine de caractère attribuée à la variable'
            //             'name' => $name,
            //         'tableau' => $tableau
            //     ]);
            // }
            
            
    // récupérer les données de la BDD en passant par l'entityManager
    // public function index(EntityManagerInterface $entityManager): Response
    #[Route('/entreprise', name: 'app_entreprise')]
    public function index(EntrepriseRepository $entrepriseRepository): Response
    {
            // on récupère toutes les entreprises de la base de données
            // $entreprises = $entityManager->getRepository(Entreprise::class)->findAll();
            // $entreprises = $entrepriseRepository->findAll();

            // on récupère les entreprises de la BDD et on les classe par ordre croissant
            // pour ce faire on a besoin de la méthode findBy
            // SELECT * FROM entreprise ORDER BY raisonSociale
            $entreprises = $entrepriseRepository->findBy([], ["raisonSociale" => "ASC"]);

            // on les envoie à travers la méthode render dans la vue index.html.twig: entreprise
        return $this->render('entreprise/index.html.twig', [
            // on fait passer une variable entreprise à laquelle on attribue la valeur de ce que l'on a récupéré
            'entreprises' => $entreprises
        ]);
    }
    
    // on ajoute la route
    #[Route('/entreprise/new', name: 'new_entreprise')]
    #[Route('/entreprise/{id}/edit', name: 'edit_entreprise')]
    public function new_edit(Entreprise $entreprise = null, Request $request, EntityManagerInterface $entityManager): Response
    {
        // si l'entreprise n'existe pas
        if(!$entreprise){
            // on crée un nouvel objet Entreprise
            $entreprise = new Entreprise();
        }
       
        // on attribue au formulaire les propriétés de cet objet
        $form = $this->createForm(EntrepriseType::class, $entreprise);

        // on traite la soumission du formulaire
        // on utilise la méthode handleRequest()
        $form->handleRequest($request);

        // si le forumlaire a été soumis et que le formulaire est valide
        if ($form->isSubmitted() && $form->isValid()) {

            // on récupère les données du formulaire et on les transmets à l'objet entreprise
            $entreprise = $form->getData();

            // on dit à Doctrine de persister càd préparer la requête pour l'ajout en BDD
            $entityManager->persist($entreprise);

            // Doctrine exécute la requête
            $entityManager->flush();

            // on redirige vers la liste des entreprises
            return $this->redirectToRoute('app_entreprise');
        }

        // on renvoie à la vue les données
        return $this->render('entreprise/new.html.twig', [
            'formAddEntreprise' => $form,
            // on ajoute en données l'id de l'entreprise car si l'entreprise n'existe pas, cela renverra un booléen à false
            // et on pourra s'en servir pour afficher correctement le titre de la page en fonction de l'ajout ou de l'edit
            'edit' => $entreprise->getId()
        ]);
    }

    #[Route('/entreprise/{id}/delete', name: 'delete_entreprise')]
    public function delete(Entreprise $entreprise, EntityManagerInterface $entityManager)
    {
        // Doctrine prépare (persiste) la requête
        $entityManager->remove($entreprise);
        // Doctrine exécute la requête : "DELETE FROM entreprise WHERE entreprise..."
        $entityManager->flush();
        
        // on redirige vers la liste des entreprises
        return $this->redirectToRoute('app_entreprise');
    }

    #[Route('/entreprise/{id}', name: 'show_entreprise')]
    // le paramConverter nous est utile pour récupérer l'id de l'objet qui a été passé en paramètre de show: ici Entreprise $entreprise et l'id de la route
    public function show(Entreprise $entreprise): Response
    {
        // on  envoie à travers la méthode render dans la vue show.html.twig
        return $this->render('entreprise/show.html.twig', [
            // on fait passer une variable entreprise à laquelle on attribue la valeur de ce que l'on a récupéré
            'entreprise' => $entreprise
        ]);
    }


}

templates/entreprise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des entreprises{% endblock %}

{% block body %}
    <h1>Liste des entreprises</h1>

    <a href="{{ path('new_entreprise') }}" class="btn btn-success">Ajouter une entreprise</a> <br>

    {% for entreprise in entreprises %}
        {# on indique l'élément/ l'objet qu'on veut afficher dans l'équivalent du echo #}
        {# on utilise le . pour faire référence au getter getRaisonSociale de l'entité Entreprise #}
        {# on fait référence au nom de la propriété dans le projet et non le nom dans la BDD #}
        {# <b>{{ entreprise.raisonSociale }}</b> {{' (' ~ entreprise.cp ~ ' ' ~ entreprise.ville ~ ')' }}<br> #}
        
        {# on a utilisé la méthode magique __toString donc on peut afficher la raison sociale + cp + ville #}
        <a href="{{ path('show_entreprise', {'id': entreprise.id}) }}">{{ entreprise}}</a>
        <a class="btn btn-warning" href="{{ path('edit_entreprise', {'id': entreprise.id}) }}">Éditer</a>
        <a class="btn btn-danger" href="{{ path('delete_entreprise', {'id': entreprise.id}) }}">Supprimer</a><br>
        <br>
    {% endfor %}

{% endblock %}

templates/entreprise/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une entreprise{% endblock %}

{% block body %}
    {% if edit %}
        <h1>Éditer une entreprise</h1>
        {% else %}
        <h1>Ajouter une entreprise</h1>
    {% endif %}

    {# {{ form(formAddEntreprise) }} #}

    {{ form_start(formAddEntreprise) }}
        {{ form_row(formAddEntreprise.raisonSociale) }}
        {{ form_row(formAddEntreprise.dateCreation) }}
    <div class="row">
        <div class="col-sm">
            {{ form_row(formAddEntreprise.adresse) }}
        </div>
        <div class="col-sm">
            {{ form_row(formAddEntreprise.cp) }}
        </div>
        <div class="col-sm">
            {{ form_row(formAddEntreprise.ville) }}
        </div>
    </div>
        {{ form_row(formAddEntreprise.valider) }}
    {{ form_end(formAddEntreprise) }}

{% endblock %}

templates/entreprise/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'une entreprise{% endblock %}

{% block body %}
    <h1>Détail d'une entreprise</h1>

    <h2> {{ entreprise }}</h2>
    <p>
        {# Adresse : {{entreprise.adresse }} {{ entreprise.cp }} {{entreprise.ville}} #}
        {# on utilise la méthode getAdresseComplete créée dans l'entité pour afficher l'adresse complète #}
        Adresse : {{ entreprise.adresseComplete }} <br>
        Date de création : {{ entreprise.dateCreation | date("d-m-Y") }}
    </p>
   
    <h2> Liste des employés</h2>
    {# grâce à doctrine on peut accéder directement à la collection d'employer sans avoir à passer
    par une requête pour récupérer les informations #}
    
    {% if entreprise.employes | length > 0 %}
    <table class="table" >
        <thead>
            <tr>
                <th>Employés</th>
            </tr>
        </thead>
        <tbody>
                {% for employe in entreprise.employes %}
                <tr><td><a href="{{ path('show_employe', {'id':employe.id}) }}"> {{ employe }}</a></td></tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Aucun salarié dans cette entreprise</p>
    {% endif %}


{% endblock %}